[basic]
__abs__ = "This magic method implements abs(self)."
__add__ = "This magic method implements self+other."
__and__ = "This magic method implements self&other."
__bool__ = "This magic method implements bool(self)."
__call__ = "This magic method implements calling self."
__ceil__ = "This magic method implements math.ceil(self)."
__cmp__ = "This magic method implements all six comparison operators at once."
__complex__ = "This magic method implements complex(self)."
__contains__ = "This magic method implements other in self."
__copy__ = "This magic method implements copy.copy(self)."
__deepcopy__ = "This magic method implements copy.deepcopy(self)."
__delitem__ = "This magic method implements del self[key]."
__divmod__ = "This magic method implements divmod(self, other)."
__eq__ = "This magic method implements self==other."
__float__ = "This magic method implements float(self)."
__floor__ = "This magic method implements math.floor(self)."
__floordiv__ = "This magic method implements self//other."
__format__ = "This magic method implements format(self, format_spec)."
__ge__ = "This magic method implements self>=other."
__getitem__ = "This magic method implements self[key]."
__gt__ = "This magic method implements self>other."
__hash__ = "This magic method implements hash(self)."
__iadd__ = "This magic method implements self+=other."
__iand__ = "This magic method implements self&=other."
__ifloordiv__ = "This magic method implements self//=other."
__ilshift__ = "This magic method implements self<<=other."
__imatmul__ = "This magic method implements self@=other."
__imod__ = "This magic method implements self%=other."
__imul__ = "This magic method implements self*=other."
__index__ = "This magic method implements operator.index(self)."
__init__ = "This magic method initializes self."
__int__ = "This magic method implements int(self)."
__invert__ = "This magic method implements ~self."
__ior__ = "This magic method implements self|=other."
__ipow__ = "This magic method implements self**=other."
__irshift__ = "This magic method implements self>>=other."
__isub__ = "This magic method implements self-=other."
__iter__ = "This magic method implements iter(self)."
__itruediv__ = "This magic method implements self/=other."
__ixor__ = "This magic method implements self^=other."
__le__ = "This magic method implements self<=other."
__len__ = "This magic method implements len(self)."
__lshift__ = "This magic method implements self<<other."
__lt__ = "This magic method implements self<other."
__matmul__ = "This magic method implements self@other."
__mod__ = "This magic method implements self%other."
__mul__ = "This magic method implements self*other."
__ne__ = "This magic method implements self!=other."
__neg__ = "This magic method implements -self."
__next__ = "This magic method implements next(self)."
__or__ = "This magic method implements self|other."
__pos__ = "This magic method implements +self."
__post_init__ = "This magic method completes the initialization of self."
__pow__ = "This magic method implements self**other."
__radd__ = "This magic method implements other+self."
__rand__ = "This magic method implements other&self."
__rdivmod__ = "This magic method implements divmod(other, self)."
__repr__ = "This magic method implements repr(self)."
__reversed__ = "This magic method implements reversed(self)."
__rfloordiv__ = "This magic method implements other//self."
__rlshift__ = "This magic method implements other<<self."
__rmatmul__ = "This magic method implements other@self."
__rmod__ = "This magic method implements other%self."
__rmul__ = "This magic method implements other*self."
__ror__ = "This magic method implements other|self."
__round__ = "This magic method implements round(self)."
__rpow__ = "This magic method implements other**self."
__rrshift__ = "This magic method implements other>>self."
__rshift__ = "This magic method implements self>>other."
__rsub__ = "This magic method implements other-self."
__rtruediv__ = "This magic method implements other/self."
__rxor__ = "This magic method implements other^self."
__setattr__ = "This magic method implements setattr(self, name, value)."
__setitem__ = "This magic method implements self[key]=value."
__str__ = "This magic method implements str(self)."
__sub__ = "This magic method implements self-other."
__truediv__ = "This magic method implements self/other."
__xor__ = "This magic method implements self^other."
append = "This method appends item at the end of self."
copy = "This method returns a new copy of self."
count = "This method counts the occurrences of item."
data = "This property represents the underlying data."
difference = "This method returns what is in self but not in other."
get = "This method returns self[key] if it exists, otherwise default."
index = "This method returns the index of the first occurrence."
insert = "This method inserts value at index."
intersection = "This method returns everything that is in all containers."
isdisjoint = "This method determines if self and other have no intersection."
issubset = "This method determines if self is a subset of other."
issuperset = "This method determines if self is a superset of other."
items = "This method returns all defined key-value-pairs."
keys = "This method returns all keys with a defined value."
setdefault = "This method returns the value of an item after guaranteeing its existence."
symmetric_difference = "This method returns what is either in self or in other."
union = "This method returns everything that is in any container."
values = "This method returns all values with a defined key."
